% Copyright 2021-2023, University of Cincinnati
% All rights reserved. See LICENSE file at:
% https://github.com/akshayelangovan/FASTCoD
% Additional copyright may be held by others, as reflected in the commit history.%% Code for modularized training
% Author : Akshay Elangovan

clc
close all
clear

%% Defining system specifications
S.M = 2; % Mass of quadrotor
S.m = 1; % Mass of payload
S.l = 1; % Length of rigid cable
S.J = 0.17; % Moment of inertia of quadrotor
% S.M = 1; % Mass of quadrotor
% S.m = 0.5; % Mass of payload
% S.l = 1; % Length of rigid cable
% S.J = 38.6*4.4*10^(-3); % Moment of inertia of quadrotor

S.g = 9.81; % acceleration due to gravity

S.hover_F = (S.M+S.m)*S.g; % Maximum thrust generated by quadrotor
% S.max_tau = 0.5; % Maximum torque by quadrotor
S.max_tau = 10; % Maximum torque by quadrotor

S.max_pos_error = 3; % Max position error that is expected
S.max_vel_error = 3; % Max velocity error that is expected
% S.max_vel_roll = 1; % Max roll velocity (angular) that is permitted
S.max_vel_roll = 3; % Max roll velocity (angular) that is permitted
S.x_goal = 0;
S.z_goal = 0;

%% Defining training specifications
% Fitness function parameters
P.n_controllers = 3; % no. of controllers being trained
P.nrules = 35;
P.nvar = P.nrules * P.n_controllers; % nvar is no.of variables
% 49 is the number of rules to be tuned per controller
P.trainingcase = 'a'; % could also be z when n_controllers is 2
% P.initstate = [...
%     0 -1 0 0 0 0 0 0;
%     0 1 0 0 0 0 0 0] * 2.5;
P.initstate = [...
%     0 0 pi/4 0 0 0 0 0;
%     0 0 -pi/4 0 0 0 0 0;
%     0 0 0 0 0 0 0 0];
    -3 0 0 0 0 0 0 0;
    3 0 0 0 0 0 0 0;
    0 -3 0 0 0 0 0 0;
    0 3 0 0 0 0 0 0;
    -3 -3 0 0 0 0 0 0;
    3 -3 0 0 0 0 0 0;
    -3 3 0 0 0 0 0 0;
    3 3 0 0 0 0 0 0];
P.costfuncname = @FitFun_2; % contains just the cost function equation (angular stabilization)
% fuzzy editing and ode solving is hardcoded as FitFun.m
% Note to self: Dont edit FitFun_1, instead create new function FitFun_2...
% Fuzzy parameters
P.lb = 1*ones(1,P.nvar); % lower bound of rules
P.ub = 7*ones(1,P.nvar); % upper bound of rules

P.ode = @myodefun; % function containing system equations for odesolver
% P.obj = @FitFun; % function containing cost/fitness equations
% P.obj is hardcoded into GeneticAlgorithm.m to prevent unnecessary
% communication overhead
P.fis1 = readfis('fisx_7x5'); % FIS files being tuned
P.fis2 = readfis('fisroll_7x5');
P.fis3 = readfis('fisz_noninverted_7x5');

P.framespersec = 50;
P.T = 8; % duration of animation  in seconds
P.tspan=linspace(0,P.T,P.T*P.framespersec); % Generating time span

%% Defining genetic algorithm specifications

P.M = 750; % Population size / No.of candidate solutions per generation
P.MaxGen = 50; % maximum number of generations / terminating condition

P.seed_status = 'seeded'; % type of initialization
% seed status can be 'random' which is basically random initialisation
% seed status can also be 'seeded' which initialises a random population
% with a part of it equal to a given seed

% check if length of seed is in accordance with training case
P.Pc = 0.95; % Probability of crossover
P.crossovername = 'double'; % type of crossover | can also be 'single'
P.Pm = 0.01; % Probability of mutation
P.Er = 0.1; % Elitism ratio
P.Pi = 0.01; % Probability of inversion

%% User interface
instruction = input('Do you want to "train" or "test"?  ','s');
switch instruction
    case 'train'
        tic
        disp("Commencing Training!")
        [cgcurve,avgcurve,BestPop] = GeneticAlgorithm(P,S);
        figure
        plot(1:P.MaxGen,-cgcurve)
        title('Best fitness value over generations')
        figure
        plot(1:P.MaxGen,-avgcurve,'.')
        title('Average fitness value over generations')
        BestChrom = BestPop(1);
        save('M9b.mat','BestChrom')
        save('MPop9b.mat','BestPop')
        histcurve.cgcurve = cgcurve;
        histcurve.avgcurve = avgcurve;
        save('M9b_histdata.mat','histcurve')
        disp('Training complete!!!')
        disp('Training time:')
        toc
        poolobj = gcp('nocreate');
        delete(poolobj)
    case 'test'
        disp('Running final_check.m for testing')
        disp('Check if all read files are correct')
        final_check;
    otherwise
        disp('Invalid input | Please type train or test | Stopping program')
end
 %% End       